Feature/733 738 - ui.config project
adobe/asset-share-commons pull request #739
Opened 2022-05-31 21:22 UTC by davidjgonzalez

Folded in #733 which included Maven updates, as this was required to resolve some build issues.

@kwin trying to add you as reviewer.

The main changes in this PR are:

1. Broke out OSGi configurations into a ui.config container package project
2. Updated Maven plugins per #733 
3. Moved ACLs out to RepoInit scripts since the updates from #733 complained about the ACLs (when acHandling was set to merge, it complained there were no ACL lists, when this was removed, it complained there were ACL lists... maybe a bug?). Repoinit is preferrable anyhow, so i opted for that rather than debugging the other issue.

## Related Issue

#733 

## Motivation and Context

Adobe/Jackrabbit best practices

## How Has This Been Tested?

TBD - Will deploy to fresh AEM CS after a Draft review

## Screenshots (if appropriate):

## Types of changes

- [X] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [X] I have signed the [Adobe Open Source CLA](https://opensource.adobe.com/cla.html).
- [X] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [X] I have read the **CONTRIBUTING** document.
- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests passed.

2022-06-01 05:16 UTC, kwin requested changes

2022-06-01 05:16 UTC, kwin commented on ui.config/pom.xml
> +        <dependency>
this dependency can be removed

2022-06-01 05:16 UTC, kwin commented on ui.config/pom.xml
> +                <configuration>
rather move this configuration to the parent pom

2022-06-01 05:16 UTC, kwin commented on ui.config/src/main/content/META-INF/vault/definition/.content.xml
> +<?xml version="1.0" encoding="UTF-8"?>
definitions don't need to be part of the package (redundant information, compare with https://github.com/apache/jackrabbit-filevault/blob/master/src/site/markdown/packagedefinition.md)

2022-06-01 07:59 UTC, kwin commented
> Moved ACLs out to RepoInit scripts since the updates from https://github.com/adobe/asset-share-commons/pull/733 complained about the ACLs (when acHandling was set to merge, it complained there were no ACL lists, when this was removed, it complained there were ACL lists... maybe a bug?)

I cannot reproduce. Filevault complained about unused `accessControlHandling` in module `ui.apps` (which is IMHO correct as that module doesn't contain any ACL lists).

2022-06-01 08:00 UTC, kwin commented on ui.content/pom.xml
> +                    <!--<accessControlHandling>merge</accessControlHandling>-->
just remove, as it no longer contains ACLs

2022-06-03 14:39 UTC, kwin commented
@davidjgonzalez Why were the reverts necessary?

2022-06-03 18:19 UTC, davidjgonzalez commented
@kwin the problem was I needed to create the `/conf/.../policies[cq:Page]` node in repo init to permissions it - but then the `ui.content` package couldn't deploy the `nt:unstructured` nodes under that in merge mode.

2022-06-20 14:50 UTC, davidjgonzalez commented
Validated against latest AEM CS .

2022-06-20 14:51 UTC, merged